# Generated by Django 6.0.4 on 2026-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='required_degree_type',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
