# Generated by Django 6.0.4 on 2026-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_savedJob_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
