# Generated by Django 6.0.4 on 2026-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
